---
title: "model building"
author: "Richard J Beck"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir="C:/Users/4473331/Documents/projects/006_ploidyModeling/06_ploidy_glucose/glucose_wgd/")
```


SINGLE CELL MODEL

```{r}

solve_Gi <- function(params) {
  # Extract parameters from the named vector
  V_g <- params["vg"]
  G_o <- params["Go"]
  K_g <- params["kg"]
  V_f <- params["vf"]
  K_f <- params["kf"]
  V_b <- params["vb"]
  K_b <- params["kb"]
  
  # Define the function whose root we need to find
  equation <- function(G_i) {
    left_side <- V_g * (G_o - G_i) / (K_g + G_o + G_i)
    right_side <- (V_f * G_i / (K_f + G_i)) + (V_b * G_i / (K_b + G_i))
    return(left_side - right_side)
  }
  
  # Use uniroot to find the root (G_i) of the equation
  Gi_solution <- uniroot(equation, lower = 0, upper = G_o)$root
  
  return(Gi_solution)
}

optim_par <- function(par){
  par <- abs(par)
  p1 <- c(par,Go=25)
  p2 <- c(par,Go=5)
  Gi1 <- solve_Gi(p1)
  Gi2 <- solve_Gi(p2)
  
  err <- (Gi1-Gi2)^2/(Gi1+Gi2)^2
  err
}

# Example usage:
params <- c(kg = 0.5,kb=0.1,kf=0.01,
          vg = 1,vb=0.9, vf=0.1,Go=25 )
Gi <- solve_Gi(params)
print(Gi)

p0 <- c(kg = 0.5,kb=0.1,kf=0.01,
          vg = 1,vb=0.9, vf=0.1)

opt <- optim(p0,fn=optim_par)
par <- abs(opt$par)
p1 <- c(par,Go=25)
p2 <- c(par,Go=5)
Gi1 <- solve_Gi(p1)
Gi2 <- solve_Gi(p2)

```

```{r}

mod <- function(Time, State, Pars){
  with(as.list(c(State, Pars)), {
    Rin <- vg*(Go-Gi)/(kg+Go+Gi)
    Rf <- vf*G6p/(kf+G6p)
    Rb <- G6p*vb/(kb+G6p)
    dGo <- -Rin*consume
    dGi <- Rin-kp*Gi
    dG6p <- kp*Gi-Rf-Rb
    dB <- Rb*consume
    return(list(c(dGo,dGi,dG6p,dB)))
  })
}

mm <- function(pars,df){
  pred <- pars[1]/(1+(pars[2]/df$Go)^pars[3])
  return(pred)
}
wrap_mm <- function(pars,df){
  pred <- mm(pars,df)
  sum((pred-df$Rb)^2)
}

pars <- c(kg = 0.5,kb=1,kf=0.1,
          vg = .05,vb=.045, vf=.005,kp=.2,consume=1)

y0 <- c(Go=25,Gi=1,G6p=0,B=0)
times <- seq(0,1000,1)

parsteady <- pars
parsteady["consume"] <- 0
library(rootSolve)
yss <- runsteady(y=y0,func=mod,parms=parsteady)
out <- ode(y=yss$y,times,mod,pars)
plot(out)
df <- data.frame(out)
df$Rb <- df$G6p*(pars["vg"]-pars["vf"])/(pars["kb"]+df$G6p)

p0 <- c(0.9,0.1,1)
opt <- optim(p0,wrap_mm,df=df)
df$predRb <- mm(opt$par,df)

p <- ggplot(df,aes(x=Go,y=Rb))+
  geom_line()+
  geom_line(aes(y=predRb,color="pred"))+
  scale_x_log10(limits=c(0.000000000001,25))
p
## Assume Gin is conver



```

```{r}


est_dcells <- function(xx,celltype="alive"){
  xx$bx <- xx$bx[xx$bx$label==celltype,]
  dn <- diff(xx$bx$ncells)
  dn <- c(NaN,zoo::rollmean(dn,k=2),NaN)
  xx$bx$dn <- dn/diff(xx$bx$day)[1]
  merge(xx$bx,xx$gx,by=c("day","ploidy","glucose"))
}

get_dg <- function(xx){
  
  xx$gx <- xx$gx[order(xx$gx$day),]
  xx$gx$backdiff <- c(NaN,diff(xx$gx$G))
  xx$gx$fordiff <- c(diff(xx$gx$G),NaN)
  return(xx)
}

mm <- function(pars,dat){
    rmax <- pars[1]
    g50 <- pars[2]
    n <- pars[3]
    est <- rmax*(1-dat$G^n/(dat$G^n+g50^n))
    if(dat$variable[1]=="da") est <-  rmax*(dat$G^n/(dat$G^n+g50^n))
    return(est)
}

fit_mm <- function(pars,dat){
  rmax <- pars[1]
  g50 <- pars[2]
  n <- pars[3]
  est <- rmax*(1-dat$G^n/(dat$G^n+g50^n))
  if(dat$variable[1]=="da") est <-  rmax*(dat$G^n/(dat$G^n+g50^n))
  sum((est-dat$value)^2)
}

mmg <- function(pars,mg){
  n <- pars[2]
  g50 <- pars[3]
  res <- pars[1]*mg$ncells*mg$G^n/(mg$G^n+g50^n)
  res
}

mmg2 <- function(pars,G){
  n <- pars[2]
  g50 <- pars[3]
  res <- -pars[1]*G^n/(G^n+g50^n)
  data.frame(G,C=res)
}

fit_mmg <- function(pars,mg){
  res <- mmg(pars,mg)
  sum((res-mg$dG))^2
}


xn <- readRDS("data/processed/plot_dat.Rds")
xn$bx <- xn$bx[xn$bx$id=="exp 2",]
xn$gx <- xn$gx[xn$gx$id=="exp 2",]

bx <- split(xn$bx,f=interaction(xn$bx$ploidy,
                                xn$bx$glucose,
                                xn$bx$id))
gx <- xn$gx

bx <- bx[sapply(bx,nrow)!=0]
xn <- lapply(bx, function(bxi){
  xni <- list(bx=bxi,gx=gx[gx$ploidy==bxi$ploidy[1]&
                             gx$glucose==bxi$glucose[1]&
                             gx$id==bxi$id[1],])
})



has_glucose <- sapply(xn,function(xni) !is.null(xni$gx))
xn <- xn[has_glucose]
xn <- lapply(xn,get_dg)

mg <- do.call(rbind,lapply(xn,function(xni){
  merge(xni$bx,xni$gx,by=c("day","ploidy","glucose"))
}))
mg$dG <- apply(mg[,c("backdiff","fordiff")],1,mean,na.rm=T)

mg2 <- mg[mg$label=="alive" & mg$ploidy=="2N",]
mg2$nG <- mg2$G*mg2$ncells
mg4 <- mg[mg$label=="alive" & mg$ploidy=="4N",]
mg4$nG <- mg4$G*mg4$ncells

pars <- c(0.001,1,0.01)

fmg2 <- optim(pars,fit_mmg,mg=mg2)
fmg4 <- optim(pars,fit_mmg,mg=mg4)

pars2N <- fmg2$par
names(pars2N) <- c("kg","ng","g50c")
pars4N <- fmg4$par
names(pars4N) <- c("kg","ng","g50c")

mg2$pred <- mmg(fmg2$par,mg2)
mg4$pred <- mmg(fmg4$par,mg4)

dfg <- rbind(mg2,mg4)

gpred1 <- cbind(mmg2(pars2N,G=exp(seq(0,2,0.01))),ploidy="2N")

gpred <- rbind(cbind(mmg2(pars2N,G=exp(seq(-10,2,0.1))),ploidy="2N"),
               cbind(mmg2(pars4N,G=exp(seq(-10,2,0.1))),ploidy="4N"))

dfgplt <- data.frame(G=dfg$G,C=-dfg$dG/dfg$ncells,ploidy=dfg$ploidy)

p <- ggplot(gpred,aes(x=G,y=C))+
  facet_grid(cols=vars(ploidy))+
  geom_line()+
  geom_point(data=dfgplt)+
  scale_x_log10("ncells*Glucose")+
  scale_y_continuous("glucose uptake")
p

xa <- do.call(rbind,lapply(xn,est_dcells,celltype="alive"))
xd <- do.call(rbind,lapply(xn,est_dcells,celltype="dead"))

if(mean(xa$G!=xd$G)) stop("out of expected order!")

dd <- xd$dn/xa$ncells
da <- (xa$dn+xd$dn)/xa$ncells

x <- xa
x$da <- da
x$dd <- dd


x <- reshape2::melt(x,measure.vars=c("dd","da"))
p <- ggplot(x,aes(x=G,y=value,color=variable))+
  facet_grid(cols=vars(ploidy))+
  geom_point()+
  scale_x_log10()
p


pars <- c(0.5,0.01,5)

x <- split(x,f=interaction(x$variable,x$ploidy))

xpar <- lapply(x,function(xi){
  optim(pars,fit_mm,dat=xi)$par
})

xpar2N <- c(xpar[[1]],xpar[[2]])
names(xpar2N) <- c("kd","g50d","nd","ka","g50a","na")
xpar4N <- c(xpar[[3]],xpar[[4]])
names(xpar4N) <- c("kd","g50d","nd","ka","g50a","na")

pars2N <- c(pars2N,xpar2N)
pars4N <- c(pars4N,xpar4N)

xfit <- do.call(rbind,lapply(1:length(x),function(i){
  pars <- xpar[[i]]
  df <- x[[i]]
  df$pred <- mm(pars,df)
  df
}))

xpar <- data.frame(do.call(rbind,xpar))
xpar <- cbind(xpar,do.call(rbind,lapply(rownames(xpar),function(ii){
  unlist(strsplit(ii,split="[.]"))
})))
colnames(xpar) <- c("rmax","g50","n","celltype","ploidy")
xpar <- reshape2::melt(xpar,id.vars=c("celltype","ploidy"))

p <- ggplot(xpar,aes(x=ploidy,y=value))+
  facet_grid(rows=vars(variable),cols=vars(celltype),scales="free")+
  geom_col()
p

renamr <- c(dd="death",da="growth")
xfit$variable <- renamr[xfit$variable]
p <- ggplot(xfit,aes(x=G,y=value,color=ploidy))+
  facet_grid(cols=vars(variable))+
  geom_point()+
  geom_line(aes(y=pred))+
  scale_x_log10("glucose (mM)")+
  scale_y_continuous("growth/death rate")
p

```


```{r}

source("Rscripts/models/model0.R")

x <- readRDS("data/fitting/fit_dat.Rds")
ploidy <- "2N"

glucose <- 5
gname <- "ic_G1_5"

bx <- x$bx1[x$bx1$glucose==glucose&x$bx1$ploidy==ploidy,]
gx <- x$gx1[x$gx1$glucose==glucose&x$gx1$ploidy==ploidy,]

x <- list(bx=bx,gx=gx)

pars<-c(kp=0.5/24,kd=1/24,kbys=0.01,theta=30000,v=0.00001,Gmin=0.05,Gstar=0.1,
        ic_N1=500,ic_G1_0p5=glucose)
names(pars[length(pars)]) <- gname

pars <- unpack_pars(pars)
pars$exp1$glucose <- glucose
y <- run_experiment(par = pars$pars,gs=NULL,ics=pars$exp1,
                       bx=dat$bx1[dat$bx1$ploidy==ploidy,],
                       gx=dat$gx1[dat$gx1$ploidy==ploidy,])

p <- ggplot(x$gx,aes(x=day,y=G))+
  facet_grid(cols=vars(ploidy),rows=vars(glucose),scales="free")+
  geom_point()+
  geom_errorbar(aes(ymin=G-sd,ymax=G+sd))+
  geom_line(data=y$gx)
p

p <- ggplot(x$bx,aes(x=day,y=ncells,color=label))+
  facet_grid(cols=vars(ploidy),rows=vars(glucose),scales="free")+
  geom_point()+
  geom_errorbar(aes(ymin=ncells-sd,ymax=ncells+sd))+
  geom_line(data=y$bx,aes(group=label))
p

```

```{r}
N0 <- 500
G0 <- bx$glucose[1]
y0 <- c(N=N0,D=0,G=G0)

out <- run_mod(pars,times,y0)

ics <- data.frame(N=N0,glucose=G0,G=G0)

wrap_opt <- function(par,gs,ics,bx,gx){
  par <- exp(par)
  err <- err_experiment(par,gs,ics,bx,gx)
  print(err)
}

p0 <- log(pars)
opt <- optim(p0,fn=wrap_opt,gs=NULL,ics=ics,bx=bx,gx=gx)

err_experiment(opt$par,gs=NULL,ics,bx,gx)

```

```{r}

opt_df <- function(par,df){
  par <- exp(par)
  pred <- -par[1]+df$dn*par[2]+df$sn*par[3]
  sum((pred-df$glucose)^2)
}

pred_df <- function(par,df){
  par <- exp(par)
  -par[1]+df$dn*par[2]+df$sn*par[3]
}

summary_df <- function(bxi){
  bxi <- bxi[bxi$label=="alive",]
  bxi <- split(bxi,f=interaction(bxi$ploidy,bxi$glucose))

  df <- do.call(rbind,lapply(bxi,function(bxij){
  dn <- max(bxij$ncells)-bxij$ncells[1]
  sn <- sum(bxij$ncells)
  data.frame(dn,sn,glucose=bxij$glucose[1],ploidy=bxij$ploidy[1])
}))
  df
}
x <- readRDS("data/fitting/fit_dat.Rds")

df1 <- summary_df(x$bx1)
df2 <- summary_df(x$bx2)

Ntrial <- 100

fit <- do.call(rbind,lapply(1:Ntrial,function(i){
  p0 <- exp(-runif(3)*10)
  fit <- optim(p0,fn=opt_df,df=df1)
  c(err=fit$value,fit$par)
}))
print(min(fit[,"err"]))
par <- fit[fit[,"err"]==min(fit[,"err"]),2:4] 
df1$pred <- pred_df(par,df=df1)
df1
```

```{r}



gf <- function(t) return(1/t^2)
mod <- function(Time, State, Pars){
  with(as.list(c(State, Pars)), {
    
    G <- gf(Time)
    dN <- kp*N*(1-N/theta)*1/(1+(g50a/G)^na)-kd*N*(1-1/(1+(g50d/G)^nd))-kd2*N^2/theta
    dD <- kd*N*(1-1/(1+(g50d/G)^nd))+kd2*N^2/theta
    return(list(c(dN,dD)))
  })
}

x <- readRDS("data/fitting/fit_dat.Rds")
gs <- readRDS("data/fitted_parameters/glucose_struct.Rds")
gx <- x$gx2
gx <- gx[gx$ploidy=="2N" & gx$glucose==1,]
gx$G <- gs$qp(gx$lum,q=0.5,gpar = gs$gpar)*gx$dilution

sf <- smooth.spline(gx$day,gx$G,df = 4)





pars<-c(kp=0.1,kd=0.1,kd2=0.01,v1=0.00001,v2=0.00001,theta=10000,g50a=0.2,na=1,g50d=0.01,nd=1)
y <- c(N=500,D=0)
times <- seq(0,7,0.01)
G <- predict(sf,times)
out <- ode(y,times,mod,pars)

plot(G)

plot(out)

```

More thought on the glucose dynamics...

```{r}

xn <- readRDS("data/fitting/fitting_data.Rds")
xn <- xn[sapply(xn,function(yi) !is.null(yi$gx))]
xn <- xn[grepl("4N",names(xn))]
df <- do.call(rbind,lapply(xn,function(xi){
  bx <- xi$bx
na <- bx$ncells[bx$metric=="alive"]
nd <- bx$ncells[bx$metric=="dead"]
ntot <- na+nd
dcells <- max(ntot)-na[1]
na <- cbind(na[-1],na[-length(na)])
ntot <- sum(rowMeans(na) * diff(bx$day[bx$metric=="alive"]))
g <- as.numeric(bx$glucose[1])
data.frame(g,ntot,dcells)  
}))

fit <- lm(g~ntot+dcells,data=df)
df$res <- predict(fit)
fit$coefficients
plot(df$res,df$g)
```

```{r}
pars2N <- readRDS("data/fitted_parameters/init_2N.Rds")
pars4N <- readRDS("data/fitted_parameters/init_4N.Rds")
xn1 <- readRDS("data/raw/221112_ilastik_counts.Rds")
colnames(xn1)[2] <- "metric"
xn2 <- readRDS("data/raw/220823_ilastik_counts.Rds")
colnames(xn2)[2] <- "metric"
xn1$day <- (xn1$frame*8+8)/24
xn2$day <- (xn2$frame*8+8)/24

gx <- readRDS("data/processed/221112_glucose.Rds")

N0 <- 700

outn1 <- do.call(rbind,lapply(unique(xn1$glucose),function(gi){
  rbind(run_mod(pars=pars2N,ploidy="2N",gluconc=gi,N0=550),
        run_mod(pars=pars4N,ploidy="4N",gluconc=gi,N0=500))
  
}))
outn2 <- do.call(rbind,lapply(unique(xn2$glucose),function(gi){
  rbind(run_mod(pars=pars2N,ploidy="2N",gluconc=gi,N0=750),
        run_mod(pars=pars4N,ploidy="4N",gluconc=gi,N0=675))
  
}))


pn1 <- ggplot(xn1,aes(x=day,y=ncells,color=metric))+
  facet_grid(rows=vars(glucose),cols=vars(ploidy),scales="free")+
  geom_point()+
  geom_line(data=outn1)+
  scale_color_discrete("")+
  scale_x_continuous("days")+
  scale_y_continuous("number of cells")+
  theme_classic(base_size = 16)+
  theme(legend.position = "top")
pn1

pn2 <- ggplot(xn2,aes(x=day,y=ncells,color=metric))+
  facet_grid(rows=vars(glucose),cols=vars(ploidy),scales="free")+
  geom_point()+
  geom_line(data=outn2)+
  scale_color_discrete("")+
  scale_x_continuous("days")+
  scale_y_continuous("number of cells")+
  theme_classic(base_size = 16)+
  theme(legend.position = "top")
pn2

pg <- ggplot(gx,aes(x=day,y=G))+
  facet_grid(cols=vars(ploidy),rows=vars(glucose),scales="free")+
  geom_point()+
  geom_line(data=outn1)+
  geom_line(data=outn2)
pg

```